% Compare legacy test23-style detection against current e10gb1 variants.
%
% This test branch isolates three suspected sources of mismatch:
%   1. legacy prepared MAT input vs current io_raw.load_blp_dataset(cfg_E10gb1())
%   2. fixed Fs = 667 vs inferred Fs = 1 / median(session_dx)
%   3. one-shot concatenated detection vs session-split detection
%
% Outputs:
%   tests/test24_detection_alignment_checks/outputs_e10gb1/*.mat
%   tests/test24_detection_alignment_checks/outputs_e10gb1/*.csv

this_script_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(fileparts(this_script_dir));
addpath(genpath(repo_root));

close all force;

legacy_mat_file = 'D:\Koopman_data\data_to_process\lfp\Nikos_ripples_e10gb1_sr_pl.mat';
output_dir = fullfile(this_script_dir, 'outputs_e10gb1');
if exist(output_dir, 'dir') ~= 7
    mkdir(output_dir);
end

params = struct();
params.passband = [2, 15; 30, 90; 90, 190];
params.band_labels = {'theta', 'gamma', 'ripple'};
params.L_start_range = [151, 101, 51];
params.L_extract_range = [301, 201, 101];
params.ThresRatio_range = [3.5, 4, 4];

fprintf('Loading legacy prepared MAT input...\n');
legacy = local_load_legacy_e10_data(legacy_mat_file);

fprintf('Loading current e10gb1 dataset via cfg/load_blp_dataset...\n');
cfg = cfg_E10gb1();
loader = local_load_current_e10_data(cfg);

data_alignment_table = local_compare_sources(legacy, loader);
variant_summary_table = local_build_variant_summary_table();

fprintf('Running detector variants on legacy prepared MAT, Fs = 667...\n');
legacy_fixed_cache = local_precompute_filtered_bands(legacy.state_var, legacy.Fs_fixed, params);
variant_results = local_detect_from_filtered( ...
    'legacy_mat_flat_fixed667', ...
    'legacy_prepared_mat', ...
    legacy_fixed_cache, ...
    legacy.state_var, ...
    legacy.dx, ...
    legacy.Fs_fixed, ...
    params, ...
    [], ...
    false);
variant_results(end+1) = local_detect_from_filtered( ... %#ok<SAGROW>
    'legacy_mat_segmented_fixed667', ...
    'legacy_prepared_mat', ...
    legacy_fixed_cache, ...
    legacy.state_var, ...
    legacy.dx, ...
    legacy.Fs_fixed, ...
    params, ...
    legacy.session_lengths, ...
    true);
clear legacy_fixed_cache;

fprintf('Running detector variants on current loader data, Fs = 667...\n');
loader_fixed_cache = local_precompute_filtered_bands(loader.state_var, legacy.Fs_fixed, params);
variant_results(end+1) = local_detect_from_filtered( ... %#ok<SAGROW>
    'loader_data_flat_fixed667', ...
    'current_loader', ...
    loader_fixed_cache, ...
    loader.state_var, ...
    loader.dx_ref, ...
    legacy.Fs_fixed, ...
    params, ...
    [], ...
    false);
variant_results(end+1) = local_detect_from_filtered( ... %#ok<SAGROW>
    'loader_data_segmented_fixed667', ...
    'current_loader', ...
    loader_fixed_cache, ...
    loader.state_var, ...
    loader.dx_ref, ...
    legacy.Fs_fixed, ...
    params, ...
    loader.session_lengths, ...
    true);
clear loader_fixed_cache;

fprintf('Running detector variants on current loader data, Fs inferred from median(session_dx)...\n');
loader_dx_cache = local_precompute_filtered_bands(loader.state_var, loader.Fs_from_dx, params);
variant_results(end+1) = local_detect_from_filtered( ... %#ok<SAGROW>
    'loader_data_flat_dxfs', ...
    'current_loader', ...
    loader_dx_cache, ...
    loader.state_var, ...
    loader.dx_ref, ...
    loader.Fs_from_dx, ...
    params, ...
    [], ...
    false);
variant_results(end+1) = local_detect_from_filtered( ... %#ok<SAGROW>
    'loader_data_segmented_dxfs_current', ...
    'current_loader', ...
    loader_dx_cache, ...
    loader.state_var, ...
    loader.dx_ref, ...
    loader.Fs_from_dx, ...
    params, ...
    loader.session_lengths, ...
    true);
clear loader_dx_cache;

variant_count_table = local_build_variant_count_table(variant_results, params.band_labels);

reference_variant_name = 'legacy_mat_flat_fixed667';
peak_match_table = local_build_peak_match_table(variant_results, reference_variant_name, params.band_labels);
aggregate_match_table = local_build_aggregate_match_table(peak_match_table);

saved_result_alignment_table = local_compare_against_saved_current_result( ...
    cfg, loader, variant_results, 'loader_data_segmented_dxfs_current', params.band_labels);

save_file = fullfile(output_dir, 'e10gb1_detection_variant_comparison.mat');
save(save_file, ...
    'cfg', ...
    'params', ...
    'legacy', ...
    'loader', ...
    'variant_results', ...
    'data_alignment_table', ...
    'variant_summary_table', ...
    'variant_count_table', ...
    'peak_match_table', ...
    'aggregate_match_table', ...
    'saved_result_alignment_table', ...
    '-v7.3');

writetable(data_alignment_table, fullfile(output_dir, 'data_alignment_table.csv'));
writetable(variant_summary_table, fullfile(output_dir, 'variant_summary_table.csv'));
writetable(variant_count_table, fullfile(output_dir, 'variant_count_table.csv'));
writetable(peak_match_table, fullfile(output_dir, 'peak_match_table.csv'));
writetable(aggregate_match_table, fullfile(output_dir, 'aggregate_match_table.csv'));
writetable(saved_result_alignment_table, fullfile(output_dir, 'saved_result_alignment_table.csv'));

disp('Aggregate match summary vs legacy_mat_flat_fixed667:');
disp(aggregate_match_table);

disp('Saved-result alignment summary vs loader_data_segmented_dxfs_current:');
disp(saved_result_alignment_table);

fprintf('Saved comparison outputs to:\n  %s\n', output_dir);


function legacy = local_load_legacy_e10_data(legacy_mat_file)
S = load(legacy_mat_file);

if ~isfield(S, 'sr_lfp') || ~isfield(S, 'pl_lfp')
    error('Legacy MAT file must contain sr_lfp and pl_lfp.');
end
if ~isfield(S, 'dx_blp') || ~isfield(S, 'segL')
    error('Legacy MAT file must contain dx_blp and segL.');
end

legacy = struct();
legacy.source_name = 'legacy_prepared_mat';
legacy.state_var = [double(S.sr_lfp).'; double(S.pl_lfp).'];
legacy.dx = double(S.dx_blp);
legacy.Fs_fixed = 667;
legacy.session_lengths = double(S.segL(:));
legacy.region_labels = {'sr', 'pl'};
if isfield(S, 'sr_ch') && isfield(S, 'pl_ch')
    legacy.selected_channel_ids = [double(S.sr_ch(:)); double(S.pl_ch(:))];
else
    legacy.selected_channel_ids = transpose(1:size(legacy.state_var, 1));
end
legacy.channel_labels = local_build_channel_labels( ...
    {'sr', 'pl'}, ...
    [size(S.sr_lfp, 2), size(S.pl_lfp, 2)]);
legacy.total_samples = size(legacy.state_var, 2);
legacy.n_channels = size(legacy.state_var, 1);
end


function loader = local_load_current_e10_data(cfg)
D = io_raw.load_blp_dataset(cfg);

loader = struct();
loader.source_name = 'current_loader';
loader.state_var = transpose(double(D.data));
loader.dx_ref = median(double(D.session_dx(:)));
loader.Fs_from_dx = 1 / loader.dx_ref;
loader.session_lengths = double(D.session_lengths(:));
loader.selected_channels = double(D.selected_channels(:));
loader.channel_labels = local_build_channel_labels( ...
    cfg.channels.selected_labels(:).', ...
    [numel(cfg.channels.selected_site1), numel(cfg.channels.selected_site2)]);
loader.total_samples = size(loader.state_var, 2);
loader.n_channels = size(loader.state_var, 1);
loader.session_ids = double(D.session_ids(:));
loader.session_dx = double(D.session_dx(:));
end


function labels = local_build_channel_labels(region_labels, counts_per_region)
labels = strings(sum(counts_per_region), 1);
idx = 0;
for r = 1:numel(region_labels)
    for k = 1:counts_per_region(r)
        idx = idx + 1;
        labels(idx) = sprintf('%s_%02d', char(string(region_labels{r})), k);
    end
end
end


function tbl = local_compare_sources(legacy, loader)
if legacy.total_samples ~= loader.total_samples || legacy.n_channels ~= loader.n_channels
    tbl = table( ...
        ["legacy_prepared_mat"; "current_loader"], ...
        [legacy.total_samples; loader.total_samples], ...
        [legacy.n_channels; loader.n_channels], ...
        [legacy.dx; loader.dx_ref], ...
        'VariableNames', {'source_name', 'total_samples', 'n_channels', 'dx'});
    return;
end

rows = cell(loader.n_channels, 1);
for c = 1:loader.n_channels
    x = double(legacy.state_var(c, :));
    y = double(loader.state_var(c, :));
    diff_xy = y - x;

    rows{c} = table( ...
        c, ...
        legacy.channel_labels(c), ...
        loader.channel_labels(c), ...
        max(abs(diff_xy)), ...
        mean(abs(diff_xy)), ...
        sqrt(mean(diff_xy .^ 2)), ...
        max(abs(diff_xy)) == 0, ...
        'VariableNames', { ...
            'channel_idx', ...
            'legacy_channel_label', ...
            'loader_channel_label', ...
            'max_abs_diff', ...
            'mean_abs_diff', ...
            'rmse', ...
            'exact_match'});
    clear x y diff_xy;
end

tbl = vertcat(rows{:});
end


function tbl = local_build_variant_summary_table()
tbl = table( ...
    [ ...
        "legacy_mat_flat_fixed667"; ...
        "legacy_mat_segmented_fixed667"; ...
        "loader_data_flat_fixed667"; ...
        "loader_data_segmented_fixed667"; ...
        "loader_data_flat_dxfs"; ...
        "loader_data_segmented_dxfs_current"], ...
    [ ...
        "legacy_prepared_mat"; ...
        "legacy_prepared_mat"; ...
        "current_loader"; ...
        "current_loader"; ...
        "current_loader"; ...
        "current_loader"], ...
    [ ...
        "sr_pl_from_legacy_mat"; ...
        "sr_pl_from_legacy_mat"; ...
        "hp_pl_from_cfg_loader"; ...
        "hp_pl_from_cfg_loader"; ...
        "hp_pl_from_cfg_loader"; ...
        "hp_pl_from_cfg_loader"], ...
    [667; 667; 667; 667; NaN; NaN], ...
    [false; true; false; true; false; true], ...
    [false; true; false; true; false; true], ...
    [ ...
        "Closest to test23 reference detector"; ...
        "Adds session splitting on top of the legacy data source"; ...
        "Swaps only the input data source to current cfg/load_blp_dataset"; ...
        "Current data source plus session-boundary handling"; ...
        "Current data source plus inferred Fs, still no session split"; ...
        "Closest to current compute_blp_bandpass_events output"], ...
    'VariableNames', { ...
        'variant_name', ...
        'data_source', ...
        'channel_layout', ...
        'Fs_fixed_if_applicable', ...
        'is_session_split', ...
        'enforce_segment_window_bounds', ...
        'interpretation'});
end


function filtered_cache = local_precompute_filtered_bands(state_var, Fs, params)
n_bands = size(params.passband, 1);
filtered_cache = cell(n_bands, 1);

for b = 1:n_bands
    fprintf('  Filtering band %d/%d at Fs = %.12g Hz ...\n', b, n_bands, Fs);
    filtered_cache{b} = transpose(double(filterSignal_mirror( ...
        transpose(state_var), ...
        Fs, ...
        params.passband(b, 1), ...
        params.passband(b, 2), ...
        1)));
end
end


function result = local_detect_from_filtered( ...
    variant_name, data_source, filtered_cache, state_var, dx, Fs, params, session_lengths, enforce_segment_bounds)
n_bands = size(params.passband, 1);
n_channels = size(state_var, 1);
L_total = size(state_var, 2);

[session_start_idx, session_end_idx] = local_resolve_session_bounds(L_total, session_lengths);
DetectResults = cell(n_bands, n_channels);

for b = 1:n_bands
    filtered_band = filtered_cache{b};

    for c = 1:n_channels
        trace_all = double(filtered_band(c, :));
        threshold = mean(trace_all, 'omitnan') + ...
            params.ThresRatio_range(b) * std(trace_all, 0, 'omitnan');

        loc_pooled = zeros(0, 1);
        loc_peak = zeros(0, 1);
        event_win = zeros(0, 2);

        for k = 1:numel(session_start_idx)
            idx1 = session_start_idx(k);
            idx2 = session_end_idx(k);

            trace_seg = trace_all(idx1:idx2);
            loc_seg = find(trace_seg > threshold);
            if ~isempty(loc_seg)
                loc_seg(1) = [];
            end

            if isempty(loc_seg)
                continue;
            end

            loc_pooled = [loc_pooled; idx1 + loc_seg(:) - 1]; %#ok<AGROW>
            loc_peak_local = find_peak_loc(trace_seg, loc_seg, params.L_extract_range(b));
            if isempty(loc_peak_local)
                continue;
            end

            loc_peak_global = idx1 + loc_peak_local(:) - 1;
            n_new = numel(loc_peak_local);
            tmp_win = zeros(n_new, 2);
            for i = 1:n_new
                tmp_win(i, 1) = loc_peak_local(i) - params.L_start_range(b) + 1;
                tmp_win(i, 2) = tmp_win(i, 1) + params.L_extract_range(b) - 1;
            end

            if enforce_segment_bounds
                keep_mask = tmp_win(:, 1) >= 1 & tmp_win(:, 2) <= numel(trace_seg);
                loc_peak_global = loc_peak_global(keep_mask);
                tmp_win = tmp_win(keep_mask, :);
            end

            if isempty(tmp_win)
                continue;
            end

            tmp_win = tmp_win + idx1 - 1;
            loc_peak = [loc_peak; loc_peak_global]; %#ok<AGROW>
            event_win = [event_win; tmp_win]; %#ok<AGROW>
        end

        out = struct();
        out.threshold = threshold;
        out.loc_pooled = loc_pooled;
        out.loc_peak = loc_peak;
        out.event_win = event_win;
        out.event_count = size(event_win, 1);
        out.peak_count = numel(loc_peak);
        DetectResults{b, c} = out;
    end
end

result = struct();
result.variant_name = char(string(variant_name));
result.data_source = char(string(data_source));
result.Fs = double(Fs);
result.dx = double(dx);
result.is_session_split = ~isempty(session_lengths);
result.enforce_segment_bounds = logical(enforce_segment_bounds);
result.session_lengths = double(session_lengths(:));
result.DetectResults = DetectResults;
end


function [session_start_idx, session_end_idx] = local_resolve_session_bounds(L_total, session_lengths)
if nargin < 2 || isempty(session_lengths)
    session_start_idx = 1;
    session_end_idx = L_total;
    return;
end

session_lengths = double(session_lengths(:));
if sum(session_lengths) ~= L_total
    error('Session lengths sum to %d, but total length is %d.', sum(session_lengths), L_total);
end

session_end_idx = cumsum(session_lengths);
session_start_idx = [1; session_end_idx(1:end-1) + 1];
end


function tbl = local_build_variant_count_table(variant_results, band_labels)
rows = cell(0, 1);
for v = 1:numel(variant_results)
    DetectResults = variant_results(v).DetectResults;
    [n_bands, n_channels] = size(DetectResults);
    for b = 1:n_bands
        variant_name = repmat(string(variant_results(v).variant_name), n_channels, 1);
        band_label = repmat(string(band_labels{b}), n_channels, 1);
        channel_idx = transpose(1:n_channels);
        event_count = zeros(n_channels, 1);
        peak_count = zeros(n_channels, 1);
        for c = 1:n_channels
            event_count(c) = double(DetectResults{b, c}.event_count);
            peak_count(c) = double(DetectResults{b, c}.peak_count);
        end
        rows{end+1, 1} = table( ... %#ok<AGROW>
            variant_name, band_label, channel_idx, event_count, peak_count);
    end
end
tbl = vertcat(rows{:});
end


function tbl = local_build_peak_match_table(variant_results, reference_variant_name, band_labels)
ref_idx = find(strcmp({variant_results.variant_name}, reference_variant_name), 1, 'first');
if isempty(ref_idx)
    error('Reference variant "%s" was not found.', reference_variant_name);
end

ref_result = variant_results(ref_idx);
rows = cell(0, 1);

for v = 1:numel(variant_results)
    if v == ref_idx
        continue;
    end

    [n_bands, n_channels] = size(ref_result.DetectResults);
    for b = 1:n_bands
        for c = 1:n_channels
            ref_peaks = double(ref_result.DetectResults{b, c}.loc_peak(:));
            var_peaks = double(variant_results(v).DetectResults{b, c}.loc_peak(:));

            shared_peaks = intersect(ref_peaks, var_peaks);
            union_peaks = union(ref_peaks, var_peaks);

            if isempty(union_peaks)
                jaccard = 1;
            else
                jaccard = numel(shared_peaks) / numel(union_peaks);
            end

            rows{end+1, 1} = table( ... %#ok<AGROW>
                string(reference_variant_name), ...
                string(variant_results(v).variant_name), ...
                string(band_labels{b}), ...
                c, ...
                numel(ref_peaks), ...
                numel(var_peaks), ...
                numel(shared_peaks), ...
                numel(setdiff(ref_peaks, var_peaks)), ...
                numel(setdiff(var_peaks, ref_peaks)), ...
                jaccard, ...
                'VariableNames', { ...
                    'reference_variant', ...
                    'variant_name', ...
                    'band_label', ...
                    'channel_idx', ...
                    'ref_peak_count', ...
                    'variant_peak_count', ...
                    'shared_peak_count', ...
                    'ref_only_peak_count', ...
                    'variant_only_peak_count', ...
                    'peak_jaccard'});
        end
    end
end

tbl = vertcat(rows{:});
end


function tbl = local_build_aggregate_match_table(peak_match_table)
variant_names = unique(peak_match_table.variant_name, 'stable');
rows = cell(numel(variant_names), 1);

for i = 1:numel(variant_names)
    idx = peak_match_table.variant_name == variant_names(i);
    ref_peak_count = sum(peak_match_table.ref_peak_count(idx));
    variant_peak_count = sum(peak_match_table.variant_peak_count(idx));
    shared_peak_count = sum(peak_match_table.shared_peak_count(idx));

    recall_vs_ref = shared_peak_count / max(ref_peak_count, 1);
    precision_vs_ref = shared_peak_count / max(variant_peak_count, 1);

    rows{i} = table( ...
        variant_names(i), ...
        ref_peak_count, ...
        variant_peak_count, ...
        shared_peak_count, ...
        recall_vs_ref, ...
        precision_vs_ref, ...
        mean(peak_match_table.peak_jaccard(idx)), ...
        min(peak_match_table.peak_jaccard(idx)), ...
        max(peak_match_table.peak_jaccard(idx)), ...
        'VariableNames', { ...
            'variant_name', ...
            'ref_peak_count_total', ...
            'variant_peak_count_total', ...
            'shared_peak_count_total', ...
            'recall_vs_ref', ...
            'precision_vs_ref', ...
            'mean_peak_jaccard', ...
            'min_peak_jaccard', ...
            'max_peak_jaccard'});
end

tbl = vertcat(rows{:});
end


function tbl = local_compare_against_saved_current_result(cfg, loader, variant_results, variant_name, band_labels)
variant_idx = find(strcmp({variant_results.variant_name}, variant_name), 1, 'first');
if isempty(variant_idx)
    error('Variant "%s" was not found.', variant_name);
end

output_root = io_project.get_project_processed_root();
[R_saved, source_event_file] = io_results.load_event_results(cfg, output_root, []);
saved_result = local_extract_saved_detect_result(R_saved);
current_result = variant_results(variant_idx);

rows = cell(0, 1);
for b = 1:numel(band_labels)
    for c = 1:loader.n_channels
        saved_peaks = double(saved_result.DetectResults{b, c}.loc_peak(:));
        test_peaks = double(current_result.DetectResults{b, c}.loc_peak(:));
        shared_peaks = intersect(saved_peaks, test_peaks);
        union_peaks = union(saved_peaks, test_peaks);

        if isempty(union_peaks)
            jaccard = 1;
        else
            jaccard = numel(shared_peaks) / numel(union_peaks);
        end

        rows{end+1, 1} = table( ... %#ok<AGROW>
            string(source_event_file), ...
            string(variant_name), ...
            string(band_labels{b}), ...
            c, ...
            numel(saved_peaks), ...
            numel(test_peaks), ...
            numel(shared_peaks), ...
            jaccard, ...
            'VariableNames', { ...
                'saved_result_file', ...
                'test_variant_name', ...
                'band_label', ...
                'channel_idx', ...
                'saved_peak_count', ...
                'test_peak_count', ...
                'shared_peak_count', ...
                'peak_jaccard'});
    end
end

tbl = vertcat(rows{:});
end


function result = local_extract_saved_detect_result(R_saved)
[n_bands, n_channels] = size(R_saved.DetectResults);
DetectResults = cell(n_bands, n_channels);
for b = 1:n_bands
    for c = 1:n_channels
        src = R_saved.DetectResults{b, c};
        out = struct();
        out.loc_peak = double(src.loc_peak(:));
        out.loc_pooled = double(src.loc_pooled(:));
        out.event_win = double(src.event_win);
        out.event_count = size(out.event_win, 1);
        out.peak_count = numel(out.loc_peak);
        DetectResults{b, c} = out;
    end
end

result = struct();
result.variant_name = 'saved_event_detection';
result.DetectResults = DetectResults;
end
