function spec = build_bold_cortical_subcortical_partition_defaults()
%BUILD_BOLD_CORTICAL_SUBCORTICAL_PARTITION_DEFAULTS Default ROI partition for bar-summary plots.
%
% This helper centralizes the default cortical/subcortical grouping used by
% ROI-average Koopman mode summary plots. Update this file if the default
% separator or ROI membership should change.

spec = struct();
spec.partition_name = 'cortical_subcortical';
spec.separator_strategy = 'after_last_cortical_roi_in_plot_order';
spec.separator_after_roi_name = '';

spec.cortical_exact_names = { ...
    'ParPrec', 'ParIntra', 'ParLat', ...
    'TmpVis', 'TmpSTS', 'TmpPol', 'TmpAu', ...
    'V5', 'V4', 'V2V3', 'pV1', 'pfV1', 'fV1', 'V1', ...
    'dlPFC', 'medPFC', 'orbPFC', 'RetroSp', 'PCC', 'dACC', 'ACC', ...
    'aIns', 'Ins', 'S2', 'S1', 'Motor', 'Premotor', 'PirFo', 'Ent'};
spec.cortical_contains_tokens = {};

spec.subcortical_exact_names = { ...
    'LGN', 'Pul', 'Tha', 'HP', ...
    'basalAmy', 'Amy', 'HTh', ...
    'VTA', 'SN', 'GP', 'DS', 'VS', ...
    'NBM', 'BNST', 'MSDB', ...
    'PAG', 'InfCol', 'SC', 'MesE', ...
    'LC_CGn', 'Raphe', 'PontReg', ...
    'DCbN', 'pflCb', 'LatHemCb', 'IntHemCb', 'alCb', 'Vermis', ...
    'Brainstem', 'ParabrachialN', ...
    'ele_LGN', 'ele_HP'};
spec.subcortical_contains_tokens = {};
end
