function save_paths = empty_residual_cross_correlation_save_paths()
%EMPTY_RESIDUAL_CROSS_CORRELATION_SAVE_PATHS Standard empty save-path struct.

save_paths = struct( ...
    'main_mat', '', ...
    'session_corr_csv', '', ...
    'pooled_corr_csv', '', ...
    'pooled_top_csv', '', ...
    'mode_csv', '', ...
    'session_summary_csv', '');
end
