"""Analyze P8/P10 xcorr hits with P5 strict P2-band subprocess labels.

This is the standardized complex-split branch used for the current
cross-dataset narrative check.  It joins P8/P10 top xcorr rows to the P5
band-event strict labels generated by ``run_pipeline5_band_selectivity.py``.
"""

from __future__ import annotations

import argparse
import csv
import math
import re
import warnings
from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterable, Sequence

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import MatplotlibDeprecationWarning
import numpy as np

warnings.filterwarnings("ignore", category=MatplotlibDeprecationWarning)


DEFAULT_PROCESSED_ROOT = Path(r"E:\DataPons_processed")
DEFAULT_DATASETS = ("e10gb1", "e10fV1", "e10gh1", "e10gw1", "f12m01", "k13m17", "k13m23")
DEFAULT_RUN_TAGS = ("pv_gsvd100", "pv_gsvd100_ds", "pv_hp100", "pv_roi")
DEFAULT_P10_FEATURES = ("efun_real", "deconv_real")
DEFAULT_TOP_N = (1, 3, 5, 10, 20, 50)
DEFAULT_RESULTS_DIR = Path("results") / "pipeline8_10_strict_band_coupling_current"
DEFAULT_FIGURE_DIR = (
    DEFAULT_PROCESSED_ROOT
    / "summary_figures"
    / "pipeline8_10_strict_band_coupling_current"
)
P5_RESULTS_SUFFIX = "p5_p2_band_event_response_v2_selective_envelope_20260528"
P5_LABEL_CSV = "component_band_event_response_v2.csv"

METHOD_ORDER = ("svd", "nmf", "mds", "umap")
K_ORDER = tuple(range(3, 9))
DENSITY_CLASS_ORDER = ("event_density", "raw_efun_density", "dimred_efun_density")
DENSITY_CLASS_LABEL = {
    "event_density": "event",
    "raw_efun_density": "raw efun",
    "dimred_efun_density": "dimred efun",
}
STRICT_LABEL_ORDER = (
    "theta_selective",
    "gamma_selective",
    "ripple_selective",
    "ripple_gamma_no_theta",
    "mixed_or_partial",
    "inactive",
    "label_missing",
)
STRICT_LABEL_COLORS = {
    "theta_selective": "#2ca25f",
    "gamma_selective": "#f2b72a",
    "ripple_selective": "#3182bd",
    "ripple_gamma_no_theta": "#756bb1",
    "mixed_or_partial": "#b26a1b",
    "inactive": "#d9d9d9",
    "label_missing": "#111111",
}
RG_LIKE_LABELS = {"gamma_selective", "ripple_selective", "ripple_gamma_no_theta"}
RUN_TAG_LABELS = {
    "pv_gsvd100": "global_svd100",
    "pv_gsvd100_ds": "gsvd100_ds",
    "pv_hp100": "HP_svd100",
    "pv_roi": "roi_mean",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--processed-root", type=Path, default=DEFAULT_PROCESSED_ROOT)
    parser.add_argument("--workspace-root", type=Path, default=Path.cwd())
    parser.add_argument("--datasets", nargs="+", default=list(DEFAULT_DATASETS))
    parser.add_argument("--run-tags", nargs="+", default=list(DEFAULT_RUN_TAGS))
    parser.add_argument("--p10-features", nargs="+", default=list(DEFAULT_P10_FEATURES))
    parser.add_argument("--top-n-values", nargs="+", type=int, default=list(DEFAULT_TOP_N))
    parser.add_argument("--component-counts", nargs="+", type=int, default=list(K_ORDER))
    parser.add_argument("--heatmap-top-n", type=int, default=10)
    parser.add_argument("--p8-save-tag", default="xcorr_csplit_standardize_rmsenv_adaptive")
    parser.add_argument("--p10-save-tag", default="dimred_xcorr_csplit_standardize_rmsenv_adaptive")
    parser.add_argument("--label-transform", default="adaptive_envelope")
    parser.add_argument("--results-dir", type=Path, default=DEFAULT_RESULTS_DIR)
    parser.add_argument("--figure-dir", type=Path, default=DEFAULT_FIGURE_DIR)
    parser.add_argument("--max-p10-dirs-per-dataset", type=int, default=0)
    return parser.parse_args()


def read_csv(path: Path, limit: int | None = None) -> list[dict[str, str]]:
    if not path.is_file():
        return []
    rows: list[dict[str, str]] = []
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            rows.append(row)
            if limit is not None and len(rows) >= limit:
                break
    return rows


def write_csv(path: Path, rows: Sequence[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields: list[str] = []
    seen: set[str] = set()
    for row in rows:
        for key in row:
            if key not in seen:
                fields.append(key)
                seen.add(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def as_float(value: object) -> float:
    try:
        out = float(str(value))
    except (TypeError, ValueError):
        return math.nan
    return out if math.isfinite(out) else math.nan


def as_int(value: object, default: int = -1) -> int:
    try:
        return int(float(str(value)))
    except (TypeError, ValueError):
        return default


def finite(values: Iterable[float]) -> list[float]:
    return [v for v in values if math.isfinite(v)]


def density_class(density_name: str) -> str:
    if density_name == "blp_evt":
        return "event_density"
    if density_name.startswith("raw_"):
        return "raw_efun_density"
    if density_name.startswith("dim_"):
        return "dimred_efun_density"
    return "other_density"


def parse_density(density_name: str) -> dict[str, object]:
    if density_name == "blp_evt":
        return {"condition": "event", "method": "", "k": "", "method_k": "", "threshold": ""}
    raw_match = re.match(r"^raw_(abs|csplit)_q(\d+)(?:_(.*))?$", density_name)
    if raw_match:
        condition, threshold, suffix = raw_match.groups()
        return {
            "condition": condition,
            "method": "raw",
            "k": "",
            "method_k": "raw",
            "threshold": threshold,
            "suffix": suffix or "",
        }
    dim_match = re.match(r"^dim_(abs|csplit)_([a-z]+)(\d+)_q(\d+)(?:_(.*))?$", density_name)
    if dim_match:
        condition, method, k, threshold, suffix = dim_match.groups()
        k_int = int(k)
        return {
            "condition": condition,
            "method": method,
            "k": k_int,
            "method_k": f"{method}_k{k_int:02d}",
            "threshold": threshold,
            "suffix": suffix or "",
        }
    return {"condition": "", "method": "", "k": "", "method_k": "", "threshold": "", "suffix": ""}


def p5_label_path(workspace_root: Path, dataset: str) -> Path:
    return workspace_root / "results" / f"{dataset}_{P5_RESULTS_SUFFIX}" / P5_LABEL_CSV


def load_p5_labels(
    workspace_root: Path,
    datasets: Sequence[str],
    label_transform: str,
) -> tuple[dict[tuple[str, str, int, int], dict[str, object]], list[dict[str, object]]]:
    labels: dict[tuple[str, str, int, int], dict[str, object]] = {}
    background_rows: list[dict[str, object]] = []
    for dataset in datasets:
        path = p5_label_path(workspace_root, dataset)
        rows = read_csv(path)
        for row in rows:
            if str(row.get("activity_transform", "")) != label_transform:
                continue
            method = str(row.get("method", "")).lower()
            k = as_int(row.get("k"))
            component = as_int(row.get("component"))
            if not method or k < 0 or component < 0:
                continue
            label = str(row.get("strict_label") or "label_missing")
            item: dict[str, object] = {
                "dataset": dataset,
                "method": method,
                "k": k,
                "method_k": f"{method}_k{k:02d}",
                "component": component,
                "strict_label": label,
                "theta_effect_z": as_float(row.get("theta_effect_z")),
                "gamma_effect_z": as_float(row.get("gamma_effect_z")),
                "ripple_effect_z": as_float(row.get("ripple_effect_z")),
                "component_timescale_sec": as_float(row.get("component_timescale_sec")),
                "envelope_window_sec": as_float(row.get("envelope_window_sec")),
                "p5_source_file": row.get("source_file", ""),
            }
            labels[(dataset.lower(), method, k, component)] = item
            background_rows.append(item)
    return labels, background_rows


def feature_family(feature: str) -> str:
    value = feature.lower()
    if "deconv" in value:
        return "deconv_efun"
    if "efun" in value:
        return "efun"
    return "other"


def parse_p10_dir(name: str) -> tuple[str, str, str, int, str]:
    match = re.match(r"^(pv_.+?)__(.+?)__([a-z]+)_k(\d+)$", name)
    if not match:
        return "", "", "", -1, ""
    run_tag, p9_feature, method, k = match.groups()
    k_int = int(k)
    return run_tag, p9_feature, method, k_int, f"{method}_k{k_int:02d}"


def join_label(
    labels: dict[tuple[str, str, int, int], dict[str, object]],
    dataset: str,
    density_name: str,
    density_index: int,
) -> dict[str, object]:
    meta = parse_density(density_name)
    if density_class(density_name) != "dimred_efun_density":
        return {}
    method = str(meta.get("method") or "")
    k = as_int(meta.get("k"))
    key = (dataset.lower(), method, k, density_index)
    return labels.get(key, {})


def source_level_from_path(path: Path) -> str:
    parts = [p.lower() for p in path.parts]
    if "feature" in parts:
        return "per_feature"
    if "density" in parts:
        return "per_density"
    return "combined"


def collect_rows_from_csv(
    *,
    pipeline: str,
    dataset: str,
    run_tag: str,
    csv_path: Path,
    rows: Sequence[dict[str, str]],
    labels: dict[tuple[str, str, int, int], dict[str, object]],
    max_n: int,
    p9_feature: str = "",
    p9_method: str = "",
    p9_k: int = -1,
    p9_method_k: str = "",
) -> list[dict[str, object]]:
    out: list[dict[str, object]] = []
    for rank, row in enumerate(rows[:max_n], start=1):
        density_name = str(row.get("density_name", "")).strip()
        dclass = density_class(density_name)
        dmeta = parse_density(density_name)
        density_index = as_int(row.get("density_index"))
        label = join_label(labels, dataset, density_name, density_index)
        strict_label = str(label.get("strict_label") or ("label_missing" if dclass == "dimred_efun_density" else ""))
        bold_feature = str(row.get("bold_feature", "")).strip()
        peak_abs = as_float(row.get("peak_abs_corr"))
        out.append(
            {
                "pipeline": pipeline,
                "dataset": dataset,
                "run_tag": run_tag,
                "bold_observable": RUN_TAG_LABELS.get(run_tag, run_tag),
                "p9_feature": p9_feature,
                "p9_method": p9_method,
                "p9_k": p9_k if p9_k >= 0 else "",
                "p9_method_k": p9_method_k,
                "source_level": source_level_from_path(csv_path),
                "source_csv": str(csv_path),
                "rank_in_source_csv": rank,
                "density_name": density_name,
                "density_class": dclass,
                "density_condition": dmeta.get("condition", ""),
                "density_method": dmeta.get("method", ""),
                "density_k": dmeta.get("k", ""),
                "density_method_k": dmeta.get("method_k", ""),
                "density_threshold": dmeta.get("threshold", ""),
                "density_suffix": dmeta.get("suffix", ""),
                "density_index": density_index,
                "density_label": row.get("density_label", ""),
                "strict_label": strict_label,
                "theta_effect_z": label.get("theta_effect_z", math.nan),
                "gamma_effect_z": label.get("gamma_effect_z", math.nan),
                "ripple_effect_z": label.get("ripple_effect_z", math.nan),
                "ripple_gamma_effect_z": max(
                    as_float(label.get("gamma_effect_z")),
                    as_float(label.get("ripple_effect_z")),
                )
                if label
                else math.nan,
                "component_timescale_sec": label.get("component_timescale_sec", math.nan),
                "envelope_window_sec": label.get("envelope_window_sec", math.nan),
                "bold_feature": bold_feature,
                "bold_feature_family": feature_family(bold_feature),
                "bold_mode_index": row.get("bold_mode_index", ""),
                "bold_component_index": row.get("bold_component_index", ""),
                "peak_abs_corr": peak_abs,
                "peak_corr": as_float(row.get("peak_corr")),
                "peak_lag_sec": as_float(row.get("peak_lag_sec")),
                "finite_peak": math.isfinite(peak_abs),
            }
        )
    return out


def collect_p8(args: argparse.Namespace, labels: dict[tuple[str, str, int, int], dict[str, object]], max_n: int) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    hits: list[dict[str, object]] = []
    availability: list[dict[str, object]] = []
    for dataset in args.datasets:
        for run_tag in args.run_tags:
            root = args.processed_root / dataset / "pipeline8_xcorr" / run_tag
            feature_files = sorted((root / "feature").glob(f"*/*{args.p8_save_tag}_peaks__*.csv"))
            density_files = sorted((root / "density").glob(f"{args.p8_save_tag}_peaks__*.csv"))
            files = feature_files if feature_files else density_files
            status = "available" if files else ("missing_root" if not root.is_dir() else "missing_peaks")
            availability.append(
                {
                    "pipeline": "P8",
                    "dataset": dataset,
                    "run_tag": run_tag,
                    "bold_observable": RUN_TAG_LABELS.get(run_tag, run_tag),
                    "status": status,
                    "n_peak_csv": len(files),
                    "root": str(root),
                }
            )
            for csv_path in files:
                rows = read_csv(csv_path, max_n)
                hits.extend(
                    collect_rows_from_csv(
                        pipeline="P8",
                        dataset=dataset,
                        run_tag=run_tag,
                        csv_path=csv_path,
                        rows=rows,
                        labels=labels,
                        max_n=max_n,
                    )
                )
    return hits, availability


def collect_p10(args: argparse.Namespace, labels: dict[tuple[str, str, int, int], dict[str, object]], max_n: int) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    hits: list[dict[str, object]] = []
    availability: list[dict[str, object]] = []
    p10_features = set(args.p10_features)
    for dataset in args.datasets:
        root = args.processed_root / dataset / "pipeline10_dimred_xcorr"
        dirs = [p for p in sorted(root.iterdir()) if p.is_dir()] if root.is_dir() else []
        if args.max_p10_dirs_per_dataset > 0:
            dirs = dirs[: args.max_p10_dirs_per_dataset]
        seen: Counter[str] = Counter()
        for p10_dir in dirs:
            run_tag, p9_feature, p9_method, p9_k, p9_method_k = parse_p10_dir(p10_dir.name)
            if run_tag not in args.run_tags:
                continue
            if p10_features and p9_feature not in p10_features:
                continue
            feature_files = sorted((p10_dir / "feature").glob(f"*/*{args.p10_save_tag}_peaks__*.csv"))
            density_files = sorted((p10_dir / "density").glob(f"{args.p10_save_tag}_peaks__*.csv"))
            files = feature_files if feature_files else density_files
            if files:
                seen[run_tag] += 1
            for csv_path in files:
                rows = read_csv(csv_path, max_n)
                hits.extend(
                    collect_rows_from_csv(
                        pipeline="P10",
                        dataset=dataset,
                        run_tag=run_tag,
                        csv_path=csv_path,
                        rows=rows,
                        labels=labels,
                        max_n=max_n,
                        p9_feature=p9_feature,
                        p9_method=p9_method,
                        p9_k=p9_k,
                        p9_method_k=p9_method_k,
                    )
                )
        for run_tag in args.run_tags:
            status = "available" if seen[run_tag] else ("missing_root" if not root.is_dir() else "missing_peaks")
            availability.append(
                {
                    "pipeline": "P10",
                    "dataset": dataset,
                    "run_tag": run_tag,
                    "bold_observable": RUN_TAG_LABELS.get(run_tag, run_tag),
                    "status": status,
                    "n_p10_dirs_with_peaks": seen[run_tag],
                    "root": str(root),
                }
            )
    return hits, availability


def context_key(row: dict[str, object]) -> tuple[object, ...]:
    return (
        row["pipeline"],
        row["dataset"],
        row["run_tag"],
        row["bold_feature_family"],
        row.get("p9_feature", ""),
        row.get("p9_method_k", ""),
    )


def build_contexts(hits: Sequence[dict[str, object]], top_n_values: Sequence[int]) -> dict[int, dict[tuple[object, ...], list[dict[str, object]]]]:
    max_n = max(top_n_values)
    grouped: dict[tuple[object, ...], list[dict[str, object]]] = defaultdict(list)
    for row in hits:
        if row.get("density_condition") not in {"event", "csplit"}:
            continue
        if not bool(row.get("finite_peak")):
            continue
        grouped[context_key(row)].append(row)
    contexts_by_n: dict[int, dict[tuple[object, ...], list[dict[str, object]]]] = {int(n): {} for n in top_n_values}
    for key, rows in grouped.items():
        ranked = sorted(rows, key=lambda r: as_float(r.get("peak_abs_corr")), reverse=True)[:max_n]
        ranked = [dict(row, rank_in_context=i) for i, row in enumerate(ranked, start=1)]
        for top_n in top_n_values:
            contexts_by_n[int(top_n)][key] = ranked[: min(int(top_n), len(ranked))]
    return contexts_by_n


def summarize_density_competition(
    contexts_by_n: dict[int, dict[tuple[object, ...], list[dict[str, object]]]],
    *,
    stratify_observable: bool = False,
) -> list[dict[str, object]]:
    out: list[dict[str, object]] = []
    for top_n, contexts in sorted(contexts_by_n.items()):
        counts: dict[tuple[str, str, str], Counter[str]] = defaultdict(Counter)
        totals: Counter[tuple[str, str, str]] = Counter()
        for key, rows in contexts.items():
            pipeline, _dataset, run_tag, family, _p9_feature, _p9_method_k = key
            if str(family) not in {"efun", "deconv_efun"}:
                continue
            observable = RUN_TAG_LABELS.get(str(run_tag), str(run_tag)) if stratify_observable else "all"
            group_key = (str(pipeline), str(family), observable)
            for row in rows:
                dclass = str(row.get("density_class"))
                if dclass not in DENSITY_CLASS_ORDER:
                    continue
                counts[group_key][dclass] += 1
                totals[group_key] += 1
        for (pipeline, family, observable), counter in sorted(counts.items()):
            total = totals[(pipeline, family, observable)]
            for dclass in DENSITY_CLASS_ORDER:
                out.append(
                    {
                        "pipeline": pipeline,
                        "bold_observable": observable,
                        "bold_feature_family": family,
                        "top_n": top_n,
                        "density_class": dclass,
                        "count": counter[dclass],
                        "fraction": counter[dclass] / total if total else math.nan,
                        "n_top_hits": total,
                    }
                )
    return out


def summarize_label_composition(
    contexts_by_n: dict[int, dict[tuple[object, ...], list[dict[str, object]]]],
    *,
    stratify_observable: bool = False,
) -> list[dict[str, object]]:
    out: list[dict[str, object]] = []
    for top_n, contexts in sorted(contexts_by_n.items()):
        counts: dict[tuple[str, str, str], Counter[str]] = defaultdict(Counter)
        totals: Counter[tuple[str, str, str]] = Counter()
        for key, rows in contexts.items():
            pipeline, _dataset, run_tag, family, _p9_feature, _p9_method_k = key
            if str(family) not in {"efun", "deconv_efun"}:
                continue
            observable = RUN_TAG_LABELS.get(str(run_tag), str(run_tag)) if stratify_observable else "all"
            for row in rows:
                if row.get("density_class") != "dimred_efun_density":
                    continue
                label = str(row.get("strict_label") or "label_missing")
                group_key = (str(pipeline), str(family), observable)
                counts[group_key][label] += 1
                totals[group_key] += 1
        for (pipeline, family, observable), counter in sorted(counts.items()):
            total = totals[(pipeline, family, observable)]
            for label in STRICT_LABEL_ORDER:
                out.append(
                    {
                        "pipeline": pipeline,
                        "bold_observable": observable,
                        "bold_feature_family": family,
                        "top_n": top_n,
                        "strict_label": label,
                        "count": counter[label],
                        "fraction_among_dimred_hits": counter[label] / total if total else math.nan,
                        "n_dimred_hits": total,
                    }
                )
    return out


def summarize_method_k_label_hits(
    contexts_by_n: dict[int, dict[tuple[object, ...], list[dict[str, object]]]],
    *,
    stratify_observable: bool = False,
) -> list[dict[str, object]]:
    out: list[dict[str, object]] = []
    for top_n, contexts in sorted(contexts_by_n.items()):
        counts: dict[tuple[str, str, str, str, str], Counter[str]] = defaultdict(Counter)
        context_counts: Counter[tuple[str, str, str, str, str]] = Counter()
        for key, rows in contexts.items():
            pipeline, _dataset, run_tag, family, _p9_feature, _p9_method_k = key
            if str(family) not in {"efun", "deconv_efun"}:
                continue
            observable = RUN_TAG_LABELS.get(str(run_tag), str(run_tag)) if stratify_observable else "all"
            for row in rows:
                if row.get("density_class") != "dimred_efun_density":
                    continue
                method = str(row.get("density_method") or "")
                k = str(row.get("density_k") or "")
                label = str(row.get("strict_label") or "label_missing")
                if not method or not k:
                    continue
                gkey = (str(pipeline), str(family), observable, method, k)
                counts[gkey][label] += 1
                context_counts[gkey] += 1
        for (pipeline, family, observable, method, k), counter in sorted(counts.items()):
            total = context_counts[(pipeline, family, observable, method, k)]
            for label in STRICT_LABEL_ORDER:
                out.append(
                    {
                        "pipeline": pipeline,
                        "bold_observable": observable,
                        "bold_feature_family": family,
                        "top_n": top_n,
                        "method": method,
                        "k": k,
                        "method_k": f"{method}_k{int(k):02d}",
                        "strict_label": label,
                        "count": counter[label],
                        "fraction_within_method_k_hits": counter[label] / total if total else math.nan,
                        "n_method_k_dimred_hits": total,
                    }
                )
    return out


def summarize_enrichment(
    label_composition: Sequence[dict[str, object]],
    background_rows: Sequence[dict[str, object]],
) -> list[dict[str, object]]:
    background = Counter(str(row.get("strict_label") or "label_missing") for row in background_rows)
    bg_total = sum(background.values())
    bg_frac = {label: background[label] / bg_total if bg_total else math.nan for label in STRICT_LABEL_ORDER}
    out: list[dict[str, object]] = []
    for row in label_composition:
        label = str(row.get("strict_label"))
        top_frac = as_float(row.get("fraction_among_dimred_hits"))
        base = bg_frac.get(label, math.nan)
        ratio = top_frac / base if math.isfinite(top_frac) and math.isfinite(base) and base > 0 else math.nan
        out.append(
            {
                **row,
                "background_fraction": base,
                "enrichment_ratio": ratio,
                "fraction_minus_background": top_frac - base if math.isfinite(top_frac) and math.isfinite(base) else math.nan,
            }
        )
    return out


def summarize_deconv_vs_efun_rg_from_label_composition(
    label_composition: Sequence[dict[str, object]],
) -> list[dict[str, object]]:
    """Compare pooled RG-like fraction among dimred hits for deconv vs efun.

    The denominator is deliberately only `dimred_efun_density` hits. Raw and
    event-density hits do not have P5 strict labels, so they are excluded from
    this fraction rather than being treated as non-RG.
    """
    accum: dict[tuple[str, str, int, str], dict[str, float]] = defaultdict(lambda: {"rg": 0.0, "total": 0.0})
    for row in label_composition:
        family = str(row.get("bold_feature_family", ""))
        if family not in {"efun", "deconv_efun"}:
            continue
        key = (str(row.get("pipeline")), str(row.get("bold_observable", "all")), as_int(row.get("top_n")), family)
        count = as_float(row.get("count"))
        if not math.isfinite(count):
            continue
        accum[key]["total"] += count
        if str(row.get("strict_label")) in RG_LIKE_LABELS:
            accum[key]["rg"] += count

    out: list[dict[str, object]] = []
    parent_keys = sorted({(pipeline, obs, top_n) for pipeline, obs, top_n, _family in accum})
    for pipeline, obs, top_n in parent_keys:
        efun = accum.get((pipeline, obs, top_n, "efun"), {"rg": 0.0, "total": 0.0})
        deconv = accum.get((pipeline, obs, top_n, "deconv_efun"), {"rg": 0.0, "total": 0.0})
        efun_frac = efun["rg"] / efun["total"] if efun["total"] > 0 else math.nan
        deconv_frac = deconv["rg"] / deconv["total"] if deconv["total"] > 0 else math.nan
        delta = deconv_frac - efun_frac if math.isfinite(efun_frac) and math.isfinite(deconv_frac) else math.nan
        ratio = deconv_frac / efun_frac if math.isfinite(efun_frac) and efun_frac > 0 and math.isfinite(deconv_frac) else math.nan
        out.append(
            {
                "pipeline": pipeline,
                "bold_observable": obs,
                "top_n": top_n,
                "efun_rg_fraction": efun_frac,
                "deconv_rg_fraction": deconv_frac,
                "deconv_minus_efun_rg_fraction": delta,
                "deconv_over_efun_rg_fraction": ratio,
                "rg_fraction_denominator": "dimred_efun_density_hits_only",
                "efun_rg_fraction_among_dimred_hits": efun_frac,
                "deconv_rg_fraction_among_dimred_hits": deconv_frac,
                "deconv_minus_efun_rg_fraction_among_dimred_hits": delta,
                "n_efun_dimred_hits": int(efun["total"]),
                "n_deconv_dimred_hits": int(deconv["total"]),
            }
        )
    return out


def summarize_deconv_vs_efun_rg_by_matched_unit(
    contexts_by_n: dict[int, dict[tuple[object, ...], list[dict[str, object]]]],
    *,
    stratify_observable: bool = False,
) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    """Compare RG-like fraction between efun and deconv within matched parent units.

    A parent unit is pipeline x dataset x run_tag x P9 feature/method-k.  This
    avoids claiming deconv is more RG-like merely because it had a different
    number of searchable contexts than efun.
    """
    unit_rows: list[dict[str, object]] = []
    for top_n, contexts in sorted(contexts_by_n.items()):
        grouped: dict[tuple[object, ...], dict[str, list[dict[str, object]]]] = defaultdict(dict)
        for key, rows in contexts.items():
            pipeline, dataset, run_tag, family, p9_feature, p9_method_k = key
            if str(family) not in {"efun", "deconv_efun"}:
                continue
            observable = RUN_TAG_LABELS.get(str(run_tag), str(run_tag)) if stratify_observable else "all"
            # P10 folders include P9 feature names such as efun_real/deconv_real.
            # For efun-vs-deconv comparison, matching on p9_feature would split
            # the two feature families into different parents.  Match by the
            # dataset/run/observable plus P9 method-k instead.
            parent_key = (str(pipeline), str(dataset), str(run_tag), observable, str(p9_method_k))
            grouped[parent_key][str(family)] = rows

        for (pipeline, dataset, run_tag, observable, p9_method_k), by_family in sorted(grouped.items()):
            if "efun" not in by_family or "deconv_efun" not in by_family:
                continue
            values: dict[str, dict[str, float]] = {}
            for family, rows in by_family.items():
                dimred = [r for r in rows if r.get("density_class") == "dimred_efun_density"]
                rg = [r for r in dimred if str(r.get("strict_label")) in RG_LIKE_LABELS]
                values[family] = {
                    "rg": float(len(rg)),
                    "total": float(len(dimred)),
                    "fraction": len(rg) / len(dimred) if dimred else math.nan,
                }
            efun_frac = values["efun"]["fraction"]
            deconv_frac = values["deconv_efun"]["fraction"]
            delta = deconv_frac - efun_frac if math.isfinite(efun_frac) and math.isfinite(deconv_frac) else math.nan
            unit_rows.append(
                {
                    "pipeline": pipeline,
                    "dataset": dataset,
                    "run_tag": run_tag,
                    "bold_observable": observable,
                    "p9_method_k": p9_method_k,
                    "top_n": top_n,
                    "efun_rg_fraction": efun_frac,
                    "deconv_rg_fraction": deconv_frac,
                    "deconv_minus_efun_rg_fraction": delta,
                    "rg_fraction_denominator": "dimred_efun_density_hits_only",
                    "efun_rg_fraction_among_dimred_hits": efun_frac,
                    "deconv_rg_fraction_among_dimred_hits": deconv_frac,
                    "deconv_minus_efun_rg_fraction_among_dimred_hits": delta,
                    "deconv_rg_gt_efun_rg": int(math.isfinite(delta) and delta > 0),
                    "deconv_rg_eq_efun_rg": int(math.isfinite(delta) and abs(delta) < 1e-12),
                    "n_efun_dimred_hits": int(values["efun"]["total"]),
                    "n_deconv_dimred_hits": int(values["deconv_efun"]["total"]),
                }
            )

    summary_groups: dict[tuple[str, str, int], list[dict[str, object]]] = defaultdict(list)
    for row in unit_rows:
        summary_groups[(str(row["pipeline"]), str(row["bold_observable"]), as_int(row["top_n"]))].append(row)
    summary_rows: list[dict[str, object]] = []
    for (pipeline, observable, top_n), rows in sorted(summary_groups.items()):
        deltas = finite(as_float(row.get("deconv_minus_efun_rg_fraction")) for row in rows)
        summary_rows.append(
            {
                "pipeline": pipeline,
                "bold_observable": observable,
                "top_n": top_n,
                "n_matched_units": len(rows),
                "rg_fraction_denominator": "dimred_efun_density_hits_only",
                "fraction_units_deconv_rg_gt_efun_rg": (
                    sum(as_int(row.get("deconv_rg_gt_efun_rg")) for row in rows) / len(rows) if rows else math.nan
                ),
                "fraction_units_deconv_rg_eq_efun_rg": (
                    sum(as_int(row.get("deconv_rg_eq_efun_rg")) for row in rows) / len(rows) if rows else math.nan
                ),
                "mean_deconv_minus_efun_rg_fraction": float(np.mean(deltas)) if deltas else math.nan,
                "median_deconv_minus_efun_rg_fraction": float(np.median(deltas)) if deltas else math.nan,
                "q25_deconv_minus_efun_rg_fraction": float(np.percentile(deltas, 25)) if deltas else math.nan,
                "q75_deconv_minus_efun_rg_fraction": float(np.percentile(deltas, 75)) if deltas else math.nan,
            }
        )
    return unit_rows, summary_rows


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def safe_name(value: object) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(value)).strip("_")


def plot_stacked_topn(
    rows: Sequence[dict[str, object]],
    *,
    pipeline: str,
    family: str,
    bold_observable: str = "all",
    category_field: str,
    value_field: str,
    order: Sequence[str],
    labels: dict[str, str],
    colors: dict[str, str],
    title: str,
    ylabel: str,
    path: Path,
) -> None:
    subset = [
        r
        for r in rows
        if r.get("pipeline") == pipeline
        and r.get("bold_feature_family") == family
        and str(r.get("bold_observable", "all")) == bold_observable
    ]
    if not subset:
        write_text_figure(path, title, ["No rows found."])
        return
    top_ns = sorted({as_int(r.get("top_n")) for r in subset if as_int(r.get("top_n")) >= 0})
    data = {(as_int(r.get("top_n")), str(r.get(category_field))): as_float(r.get(value_field)) for r in subset}
    fig, ax = plt.subplots(figsize=(12.8, 4.8))
    bottom = np.zeros(len(top_ns))
    x = np.arange(len(top_ns))
    for category in order:
        vals = np.array([data.get((n, category), 0.0) for n in top_ns], dtype=float)
        ax.bar(x, vals, bottom=bottom, label=labels.get(category, category), color=colors.get(category, "#999999"))
        bottom += np.nan_to_num(vals, nan=0.0)
    ax.set_xticks(x)
    ax.set_xticklabels([f"top{n}" for n in top_ns])
    ax.set_ylim(0, 1.0)
    ax.set_ylabel(ylabel)
    ax.set_title(title, fontsize=13, fontweight="bold")
    ax.legend(loc="center left", bbox_to_anchor=(1.02, 0.5), frameon=False)
    ax.grid(axis="y", alpha=0.25)
    fig.tight_layout()
    ensure_dir(path.parent)
    fig.savefig(path, dpi=180)
    plt.close(fig)


def write_text_figure(path: Path, title: str, lines: Sequence[str]) -> None:
    fig, ax = plt.subplots(figsize=(8, 3))
    ax.axis("off")
    ax.text(0.02, 0.90, title, fontsize=14, fontweight="bold", va="top")
    ax.text(0.02, 0.72, "\n".join(lines), fontsize=11, va="top")
    ensure_dir(path.parent)
    fig.savefig(path, dpi=160)
    plt.close(fig)


def plot_label_enrichment(
    rows: Sequence[dict[str, object]],
    *,
    pipeline: str,
    family: str,
    bold_observable: str = "all",
    top_n: int,
    path: Path,
) -> None:
    subset = [
        r
        for r in rows
        if r.get("pipeline") == pipeline
        and r.get("bold_feature_family") == family
        and str(r.get("bold_observable", "all")) == bold_observable
        and as_int(r.get("top_n")) == top_n
    ]
    if not subset:
        write_text_figure(path, f"{pipeline} strict-label enrichment top{top_n} | {family}", ["No rows found."])
        return
    labels = list(STRICT_LABEL_ORDER)
    vals = [as_float(next((r.get("enrichment_ratio") for r in subset if r.get("strict_label") == label), math.nan)) for label in labels]
    fig, ax = plt.subplots(figsize=(13.2, 4.8))
    x = np.arange(len(labels))
    ax.bar(x, [0 if not math.isfinite(v) else v for v in vals], color=[STRICT_LABEL_COLORS.get(l, "#999999") for l in labels])
    ax.axhline(1.0, color="#444444", linestyle="--", linewidth=1)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=30, ha="right")
    ax.set_ylabel("top-hit fraction / P5 background fraction")
    ax.set_title(f"{pipeline} strict-label enrichment | top{top_n} | {family}", fontsize=13, fontweight="bold")
    ax.grid(axis="y", alpha=0.25)
    fig.tight_layout()
    ensure_dir(path.parent)
    fig.savefig(path, dpi=180)
    plt.close(fig)


def plot_deconv_vs_efun_rg_enrichment(
    pooled_rows: Sequence[dict[str, object]],
    unit_summary_rows: Sequence[dict[str, object]],
    *,
    pipeline: str,
    bold_observable: str,
    path: Path,
) -> None:
    pooled = [
        r
        for r in pooled_rows
        if str(r.get("pipeline")) == pipeline and str(r.get("bold_observable", "all")) == bold_observable
    ]
    unit = [
        r
        for r in unit_summary_rows
        if str(r.get("pipeline")) == pipeline and str(r.get("bold_observable", "all")) == bold_observable
    ]
    if not pooled and not unit:
        write_text_figure(path, f"{pipeline} deconv-vs-efun RG enrichment | {bold_observable}", ["No rows found."])
        return

    top_ns = sorted({as_int(r.get("top_n")) for r in pooled + unit if as_int(r.get("top_n")) >= 0})
    pooled_lookup = {as_int(r.get("top_n")): r for r in pooled}
    unit_lookup = {as_int(r.get("top_n")): r for r in unit}

    x = np.arange(len(top_ns), dtype=float)
    efun_vals = [as_float(pooled_lookup.get(n, {}).get("efun_rg_fraction")) for n in top_ns]
    deconv_vals = [as_float(pooled_lookup.get(n, {}).get("deconv_rg_fraction")) for n in top_ns]
    delta_vals = [as_float(pooled_lookup.get(n, {}).get("deconv_minus_efun_rg_fraction")) for n in top_ns]
    win_vals = [as_float(unit_lookup.get(n, {}).get("fraction_units_deconv_rg_gt_efun_rg")) for n in top_ns]

    fig, axes = plt.subplots(1, 3, figsize=(18.5, 4.4), constrained_layout=True)
    width = 0.38
    axes[0].bar(x - width / 2, [0 if not math.isfinite(v) else v for v in efun_vals], width=width, label="efun", color="#2b83ba", alpha=0.8)
    axes[0].bar(x + width / 2, [0 if not math.isfinite(v) else v for v in deconv_vals], width=width, label="deconv_efun", color="#d95f02", alpha=0.8)
    axes[0].set_ylim(0, 1.0)
    axes[0].set_ylabel("RG-like fraction among dimred hits")
    axes[0].set_xticks(x)
    axes[0].set_xticklabels([f"top{n}" for n in top_ns])
    axes[0].legend(frameon=False)
    axes[0].grid(axis="y", alpha=0.25)

    axes[1].bar(x, [0 if not math.isfinite(v) else v for v in delta_vals], color=["#d95f02" if math.isfinite(v) and v > 0 else "#7f7f7f" for v in delta_vals])
    axes[1].axhline(0, color="#303030", linewidth=1)
    axes[1].set_ylabel("deconv dimred-hit RG fraction - efun")
    axes[1].set_xticks(x)
    axes[1].set_xticklabels([f"top{n}" for n in top_ns])
    axes[1].grid(axis="y", alpha=0.25)

    axes[2].bar(x, [0 if not math.isfinite(v) else v for v in win_vals], color="#756bb1", alpha=0.85)
    axes[2].axhline(0.5, color="#303030", linestyle="--", linewidth=1)
    axes[2].set_ylim(0, 1.0)
    axes[2].set_ylabel("matched units where deconv RG > efun RG")
    axes[2].set_xticks(x)
    axes[2].set_xticklabels([f"top{n}" for n in top_ns])
    axes[2].grid(axis="y", alpha=0.25)
    for i, n in enumerate(top_ns):
        n_units = as_int(unit_lookup.get(n, {}).get("n_matched_units"), default=0)
        if n_units:
            axes[2].text(i, min(0.98, (win_vals[i] if math.isfinite(win_vals[i]) else 0) + 0.04), f"n={n_units}", ha="center", va="bottom", fontsize=8)

    fig.suptitle(
        f"{pipeline} deconv-vs-efun RG-like subprocess enrichment among dimred hits | {bold_observable}",
        fontsize=14,
        weight="bold",
    )
    ensure_dir(path.parent)
    fig.savefig(path, dpi=180)
    plt.close(fig)


def plot_effect_scatter(
    hits: Sequence[dict[str, object]],
    contexts_by_n: dict[int, dict[tuple[object, ...], list[dict[str, object]]]],
    *,
    pipeline: str,
    family: str,
    bold_observable: str = "all",
    top_n: int,
    path: Path,
) -> None:
    _ = hits
    rows: list[dict[str, object]] = []
    for key, ctx_rows in contexts_by_n.get(top_n, {}).items():
        observable = RUN_TAG_LABELS.get(str(key[2]), str(key[2]))
        if key[0] != pipeline or key[3] != family:
            continue
        if bold_observable != "all" and observable != bold_observable:
            continue
        rows.extend([r for r in ctx_rows if r.get("density_class") == "dimred_efun_density"])
    if not rows:
        write_text_figure(path, f"{pipeline} strict effect scatter top{top_n} | {family}", ["No dimred top-hit rows found."])
        return
    fig, ax = plt.subplots(figsize=(10.8, 5.8))
    for label in STRICT_LABEL_ORDER:
        subset = [r for r in rows if str(r.get("strict_label")) == label]
        if not subset:
            continue
        x = [as_float(r.get("theta_effect_z")) for r in subset]
        y = [as_float(r.get("ripple_gamma_effect_z")) for r in subset]
        ax.scatter(x, y, s=22, alpha=0.65, color=STRICT_LABEL_COLORS.get(label, "#777777"), label=f"{label} ({len(subset)})")
    ax.axhline(0.5, color="#999999", linestyle="--", linewidth=1)
    ax.axvline(0.5, color="#999999", linestyle="--", linewidth=1)
    lim_values = finite([as_float(r.get("theta_effect_z")) for r in rows] + [as_float(r.get("ripple_gamma_effect_z")) for r in rows])
    if lim_values:
        low = min(-0.2, min(lim_values) - 0.2)
        high = max(1.5, max(lim_values) + 0.2)
        ax.set_xlim(low, high)
        ax.set_ylim(low, high)
        ax.plot([low, high], [low, high], color="#bbbbbb", linewidth=1)
    ax.set_xlabel("theta event effect z")
    ax.set_ylabel("max(gamma, ripple) event effect z")
    ax.set_title(f"{pipeline} dimred top-hit P5 band effects | top{top_n} | {family}", fontsize=12, fontweight="bold")
    ax.legend(loc="center left", bbox_to_anchor=(1.02, 0.5), frameon=False, fontsize=8)
    ax.grid(alpha=0.25)
    fig.tight_layout()
    ensure_dir(path.parent)
    fig.savefig(path, dpi=180)
    plt.close(fig)


def plot_method_k_heatmap(
    rows: Sequence[dict[str, object]],
    *,
    pipeline: str,
    family: str,
    bold_observable: str = "all",
    top_n: int,
    label: str,
    path: Path,
) -> None:
    subset = [
        r
        for r in rows
        if r.get("pipeline") == pipeline
        and r.get("bold_feature_family") == family
        and str(r.get("bold_observable", "all")) == bold_observable
        and as_int(r.get("top_n")) == top_n
        and r.get("strict_label") == label
    ]
    matrix = np.zeros((len(METHOD_ORDER), len(K_ORDER)), dtype=float)
    for r in subset:
        method = str(r.get("method"))
        k = as_int(r.get("k"))
        if method in METHOD_ORDER and k in K_ORDER:
            matrix[METHOD_ORDER.index(method), K_ORDER.index(k)] = as_float(r.get("count"))
    fig, ax = plt.subplots(figsize=(10.8, 3.6))
    im = ax.imshow(matrix, aspect="auto", cmap="YlOrRd")
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            ax.text(j, i, f"{matrix[i, j]:.0f}", ha="center", va="center", fontsize=9)
    ax.set_yticks(np.arange(len(METHOD_ORDER)))
    ax.set_yticklabels(METHOD_ORDER)
    ax.set_xticks(np.arange(len(K_ORDER)))
    ax.set_xticklabels([f"k{k:02d}" for k in K_ORDER])
    ax.set_title(f"{pipeline} {label} dimred-hit count | top{top_n} | {family}", fontsize=12, fontweight="bold")
    fig.colorbar(im, ax=ax, shrink=0.75, label="hit count")
    fig.tight_layout()
    ensure_dir(path.parent)
    fig.savefig(path, dpi=180)
    plt.close(fig)


def plot_lag_distribution(
    contexts_by_n: dict[int, dict[tuple[object, ...], list[dict[str, object]]]],
    *,
    pipeline: str,
    family: str,
    bold_observable: str = "all",
    top_n: int,
    path: Path,
) -> None:
    by_label: dict[str, list[float]] = defaultdict(list)
    for key, rows in contexts_by_n.get(top_n, {}).items():
        observable = RUN_TAG_LABELS.get(str(key[2]), str(key[2]))
        if key[0] != pipeline or key[3] != family:
            continue
        if bold_observable != "all" and observable != bold_observable:
            continue
        for row in rows:
            if row.get("density_class") != "dimred_efun_density":
                continue
            lag = as_float(row.get("peak_lag_sec"))
            if math.isfinite(lag):
                by_label[str(row.get("strict_label") or "label_missing")].append(lag)
    labels = [label for label in STRICT_LABEL_ORDER if by_label.get(label)]
    if not labels:
        write_text_figure(path, f"{pipeline} dimred lag distribution top{top_n} | {family}", ["No finite dimred lags found."])
        return
    fig, ax = plt.subplots(figsize=(13.2, 4.8))
    values = [by_label[label] for label in labels]
    bp = ax.boxplot(values, patch_artist=True, labels=labels, showfliers=False)
    for patch, label in zip(bp["boxes"], labels):
        patch.set_facecolor(STRICT_LABEL_COLORS.get(label, "#999999"))
        patch.set_alpha(0.75)
    ax.axhline(0, color="#555555", linewidth=1)
    ax.set_xticklabels(labels, rotation=25, ha="right")
    ax.set_ylabel("peak lag (s)")
    ax.set_title(f"{pipeline} dimred top-hit lag by strict label | top{top_n} | {family}", fontsize=12, fontweight="bold")
    ax.grid(axis="y", alpha=0.25)
    fig.tight_layout()
    ensure_dir(path.parent)
    fig.savefig(path, dpi=180)
    plt.close(fig)


def write_summary(
    path: Path,
    *,
    args: argparse.Namespace,
    hits: Sequence[dict[str, object]],
    availability: Sequence[dict[str, object]],
    background_rows: Sequence[dict[str, object]],
) -> None:
    missing = [r for r in availability if str(r.get("status")) != "available"]
    dimred_hits = [r for r in hits if r.get("density_class") == "dimred_efun_density"]
    label_missing = [r for r in dimred_hits if r.get("strict_label") == "label_missing"]
    lines = [
        "# P8/P10 strict band coupling summary",
        "",
        f"- Datasets: `{', '.join(args.datasets)}`",
        f"- P8 save tag: `{args.p8_save_tag}`",
        f"- P10 save tag: `{args.p10_save_tag}`",
        f"- P5 label transform: `{args.label_transform}`",
        f"- Total hit rows collected: `{len(hits)}`",
        f"- Dimred hit rows collected: `{len(dimred_hits)}`",
        "- RG-like fractions are computed among `dimred_efun_density` hits only; raw/event hits are excluded from that denominator.",
        f"- P5 label background components: `{len(background_rows)}`",
        f"- Dimred hit rows with missing strict label: `{len(label_missing)}`",
        f"- Missing P8/P10 contexts: `{len(missing)}`",
        "",
        "## Missing Contexts",
        "",
    ]
    if missing:
        for row in missing[:80]:
            lines.append(f"- {row.get('pipeline')} {row.get('dataset')} {row.get('run_tag')}: {row.get('status')}")
        if len(missing) > 80:
            lines.append(f"- ... {len(missing) - 80} more")
    else:
        lines.append("- none")
    ensure_dir(path.parent)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    global K_ORDER
    args = parse_args()
    K_ORDER = tuple(sorted({int(k) for k in args.component_counts}))
    max_n = max(args.top_n_values)
    labels, background_rows = load_p5_labels(args.workspace_root, args.datasets, args.label_transform)
    p8_hits, p8_availability = collect_p8(args, labels, max_n)
    p10_hits, p10_availability = collect_p10(args, labels, max_n)
    hits = p8_hits + p10_hits
    availability = p8_availability + p10_availability
    contexts_by_n = build_contexts(hits, args.top_n_values)

    density_competition = summarize_density_competition(contexts_by_n)
    label_composition = summarize_label_composition(contexts_by_n)
    method_k_label_hits = summarize_method_k_label_hits(contexts_by_n)
    label_enrichment = summarize_enrichment(label_composition, background_rows)
    density_competition_by_observable = summarize_density_competition(contexts_by_n, stratify_observable=True)
    label_composition_by_observable = summarize_label_composition(contexts_by_n, stratify_observable=True)
    method_k_label_hits_by_observable = summarize_method_k_label_hits(contexts_by_n, stratify_observable=True)
    label_enrichment_by_observable = summarize_enrichment(label_composition_by_observable, background_rows)
    rg_enrichment = summarize_deconv_vs_efun_rg_from_label_composition(label_composition)
    rg_enrichment_by_observable = summarize_deconv_vs_efun_rg_from_label_composition(label_composition_by_observable)
    rg_unit_rows, rg_unit_summary = summarize_deconv_vs_efun_rg_by_matched_unit(contexts_by_n)
    rg_unit_rows_by_observable, rg_unit_summary_by_observable = summarize_deconv_vs_efun_rg_by_matched_unit(
        contexts_by_n,
        stratify_observable=True,
    )

    write_csv(args.results_dir / "p8_p10_strict_band_hits_long.csv", hits)
    write_csv(args.results_dir / "p8_p10_strict_band_availability.csv", availability)
    write_csv(args.results_dir / "p5_strict_band_label_background.csv", background_rows)
    write_csv(args.results_dir / "density_class_topN_fraction.csv", density_competition)
    write_csv(args.results_dir / "dimred_strict_label_topN_fraction.csv", label_composition)
    write_csv(args.results_dir / "dimred_strict_label_enrichment.csv", label_enrichment)
    write_csv(args.results_dir / "method_k_strict_label_hit_counts.csv", method_k_label_hits)
    write_csv(args.results_dir / "density_class_topN_fraction_by_observable.csv", density_competition_by_observable)
    write_csv(args.results_dir / "dimred_strict_label_topN_fraction_by_observable.csv", label_composition_by_observable)
    write_csv(args.results_dir / "dimred_strict_label_enrichment_by_observable.csv", label_enrichment_by_observable)
    write_csv(args.results_dir / "method_k_strict_label_hit_counts_by_observable.csv", method_k_label_hits_by_observable)
    write_csv(args.results_dir / "deconv_vs_efun_rg_enrichment.csv", rg_enrichment)
    write_csv(args.results_dir / "deconv_vs_efun_rg_enrichment_by_observable.csv", rg_enrichment_by_observable)
    write_csv(args.results_dir / "deconv_vs_efun_rg_enrichment_matched_units.csv", rg_unit_rows)
    write_csv(args.results_dir / "deconv_vs_efun_rg_enrichment_matched_unit_summary.csv", rg_unit_summary)
    write_csv(args.results_dir / "deconv_vs_efun_rg_enrichment_matched_units_by_observable.csv", rg_unit_rows_by_observable)
    write_csv(args.results_dir / "deconv_vs_efun_rg_enrichment_matched_unit_summary_by_observable.csv", rg_unit_summary_by_observable)
    write_summary(
        args.results_dir / "README_strict_band_coupling_summary.md",
        args=args,
        hits=hits,
        availability=availability,
        background_rows=background_rows,
    )

    density_colors = {
        "event_density": "#9ecae1",
        "raw_efun_density": "#fdae6b",
        "dimred_efun_density": "#74c476",
    }
    for pipeline in ("P8", "P10"):
        plot_deconv_vs_efun_rg_enrichment(
            rg_enrichment,
            rg_unit_summary,
            pipeline=pipeline,
            bold_observable="all",
            path=args.figure_dir
            / "00_deconv_vs_efun_rg_enrichment"
            / f"{pipeline.lower()}_deconv_vs_efun_rg_enrichment.png",
        )
        for family in ("efun", "deconv_efun"):
            plot_stacked_topn(
                density_competition,
                pipeline=pipeline,
                family=family,
                category_field="density_class",
                value_field="fraction",
                order=DENSITY_CLASS_ORDER,
                labels=DENSITY_CLASS_LABEL,
                colors=density_colors,
                title=f"{pipeline} density-source competition | {family}",
                ylabel="fraction of topN hits",
                path=args.figure_dir / "01_density_source_competition" / f"{pipeline.lower()}_density_class_fraction__{family}.png",
            )
            plot_stacked_topn(
                label_composition,
                pipeline=pipeline,
                family=family,
                category_field="strict_label",
                value_field="fraction_among_dimred_hits",
                order=STRICT_LABEL_ORDER,
                labels={x: x for x in STRICT_LABEL_ORDER},
                colors=STRICT_LABEL_COLORS,
                title=f"{pipeline} dimred strict-label composition | {family}",
                ylabel="fraction among dimred hits",
                path=args.figure_dir / "02_dimred_strict_label_composition" / f"{pipeline.lower()}_dimred_strict_label_fraction__{family}.png",
            )
            plot_label_enrichment(
                label_enrichment,
                pipeline=pipeline,
                family=family,
                top_n=args.heatmap_top_n,
                path=args.figure_dir / "03_dimred_strict_label_enrichment" / f"{pipeline.lower()}_strict_label_enrichment_top{args.heatmap_top_n}__{family}.png",
            )
            plot_effect_scatter(
                hits,
                contexts_by_n,
                pipeline=pipeline,
                family=family,
                top_n=args.heatmap_top_n,
                path=args.figure_dir / "04_dimred_effect_scatter" / f"{pipeline.lower()}_strict_effect_scatter_top{args.heatmap_top_n}__{family}.png",
            )
            plot_lag_distribution(
                contexts_by_n,
                pipeline=pipeline,
                family=family,
                top_n=args.heatmap_top_n,
                path=args.figure_dir / "06_lag_distribution" / f"{pipeline.lower()}_lag_by_label_top{args.heatmap_top_n}__{family}.png",
            )
            for label in ("theta_selective", "gamma_selective", "ripple_selective", "ripple_gamma_no_theta", "mixed_or_partial"):
                plot_method_k_heatmap(
                    method_k_label_hits,
                    pipeline=pipeline,
                    family=family,
                    top_n=args.heatmap_top_n,
                    label=label,
                    path=args.figure_dir
                    / "05_method_k_strict_label_hit_maps"
                    / f"{pipeline.lower()}_{safe_name(label)}_method_k_hits_top{args.heatmap_top_n}__{family}.png",
                )

    observables = sorted(
        {str(row.get("bold_observable")) for row in hits if row.get("bold_observable")},
        key=lambda x: list(RUN_TAG_LABELS.values()).index(x) if x in RUN_TAG_LABELS.values() else 999,
    )
    for pipeline in ("P8", "P10"):
        for observable in observables:
            obs_slug = safe_name(observable)
            plot_deconv_vs_efun_rg_enrichment(
                rg_enrichment_by_observable,
                rg_unit_summary_by_observable,
                pipeline=pipeline,
                bold_observable=observable,
                path=args.figure_dir
                / "00_deconv_vs_efun_rg_enrichment_by_observable"
                / obs_slug
                / f"{pipeline.lower()}_deconv_vs_efun_rg_enrichment__{obs_slug}.png",
            )
            for family in ("efun", "deconv_efun"):
                plot_stacked_topn(
                    density_competition_by_observable,
                    pipeline=pipeline,
                    family=family,
                    bold_observable=observable,
                    category_field="density_class",
                    value_field="fraction",
                    order=DENSITY_CLASS_ORDER,
                    labels=DENSITY_CLASS_LABEL,
                    colors=density_colors,
                    title=f"{pipeline} density-source competition | {observable} | {family}",
                    ylabel="fraction of topN hits",
                    path=args.figure_dir
                    / "01_density_source_competition_by_observable"
                    / obs_slug
                    / f"{pipeline.lower()}_density_class_fraction__{obs_slug}__{family}.png",
                )
                plot_stacked_topn(
                    label_composition_by_observable,
                    pipeline=pipeline,
                    family=family,
                    bold_observable=observable,
                    category_field="strict_label",
                    value_field="fraction_among_dimred_hits",
                    order=STRICT_LABEL_ORDER,
                    labels={x: x for x in STRICT_LABEL_ORDER},
                    colors=STRICT_LABEL_COLORS,
                    title=f"{pipeline} dimred strict-label composition | {observable} | {family}",
                    ylabel="fraction among dimred hits",
                    path=args.figure_dir
                    / "02_dimred_strict_label_composition_by_observable"
                    / obs_slug
                    / f"{pipeline.lower()}_dimred_strict_label_fraction__{obs_slug}__{family}.png",
                )
                plot_label_enrichment(
                    label_enrichment_by_observable,
                    pipeline=pipeline,
                    family=family,
                    bold_observable=observable,
                    top_n=args.heatmap_top_n,
                    path=args.figure_dir
                    / "03_dimred_strict_label_enrichment_by_observable"
                    / obs_slug
                    / f"{pipeline.lower()}_strict_label_enrichment_top{args.heatmap_top_n}__{obs_slug}__{family}.png",
                )
                plot_effect_scatter(
                    hits,
                    contexts_by_n,
                    pipeline=pipeline,
                    family=family,
                    bold_observable=observable,
                    top_n=args.heatmap_top_n,
                    path=args.figure_dir
                    / "04_dimred_effect_scatter_by_observable"
                    / obs_slug
                    / f"{pipeline.lower()}_strict_effect_scatter_top{args.heatmap_top_n}__{obs_slug}__{family}.png",
                )
                plot_lag_distribution(
                    contexts_by_n,
                    pipeline=pipeline,
                    family=family,
                    bold_observable=observable,
                    top_n=args.heatmap_top_n,
                    path=args.figure_dir
                    / "06_lag_distribution_by_observable"
                    / obs_slug
                    / f"{pipeline.lower()}_lag_by_label_top{args.heatmap_top_n}__{obs_slug}__{family}.png",
                )
                for label in ("theta_selective", "gamma_selective", "ripple_selective", "ripple_gamma_no_theta", "mixed_or_partial"):
                    plot_method_k_heatmap(
                        method_k_label_hits_by_observable,
                        pipeline=pipeline,
                        family=family,
                        bold_observable=observable,
                        top_n=args.heatmap_top_n,
                        label=label,
                        path=args.figure_dir
                        / "05_method_k_strict_label_hit_maps_by_observable"
                        / obs_slug
                        / f"{pipeline.lower()}_{safe_name(label)}_method_k_hits_top{args.heatmap_top_n}__{obs_slug}__{family}.png",
                    )

    write_text_figure(
        args.figure_dir / "07_roi_activation_consistency" / "roi_activation_followup_needed.png",
        "ROI/activation consistency follow-up",
        [
            "Use the strict-label hit tables to select a small set of candidate groups first.",
            "Then generate ROI/activation maps only for those candidate BOLD modes.",
            "This avoids reviving broad default activation-map generation.",
        ],
    )
    print(f"Wrote hits: {len(hits)}")
    print(f"Wrote figures: {args.figure_dir}")
    print(f"Wrote tables: {args.results_dir}")


if __name__ == "__main__":
    main()
