"""Plot E10gb1 raw-csplit top5 component comparisons.

This narrow helper compares raw efun component identities for the current
non-standardized csplit branch and the E10gb1 standardized-csplit probe.
It expects the raw-csplit xcorr long CSV generated by the preceding
standardized-vs-nonstandardized comparison step.
"""

from __future__ import annotations

import csv
import math
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[1]
PROCESSED_ROOT = Path("/mnt/e/DataPons_processed")
RESULT_DIR = REPO_ROOT / "results" / "e10gb1_standardized_csplit_p8_p10_probe"
FIGURE_DIR = (
    PROCESSED_ROOT
    / "summary_figures"
    / "pipeline11_current_analysis_summary"
    / "p8_p10_e10gb1_standardized_csplit_probe"
)
LONG_FILE = RESULT_DIR / "raw_csplit_xcorr_distribution_std_vs_nonstandard_long.csv"
META_FILE = (
    REPO_ROOT
    / "results"
    / "p8_p10_parameter_selection_current_rmsenv_adaptive_v2"
    / "p5_raw_density_mode_metadata.csv"
)


def safe_float(value: object) -> float:
    try:
        out = float(value)  # type: ignore[arg-type]
    except Exception:
        return math.nan
    return out if math.isfinite(out) else math.nan


def density_name(condition: str) -> str:
    if condition == "standardized":
        return "raw_csplit_q070_standardize_rmsenv_adaptive"
    return "raw_csplit_q070_rmsenv_adaptive"


def tau_label(tau: float) -> str:
    if not math.isfinite(tau):
        return "tau=NA"
    if tau >= 10:
        return f"tau={tau:.1f}s"
    if tau >= 1:
        return f"tau={tau:.2f}s"
    if tau >= 0.001:
        return f"tau={tau * 1000:.1f}ms"
    return f"tau={tau * 1e6:.0f}us"


def load_metadata() -> dict[tuple[str, int], dict[str, float]]:
    out: dict[tuple[str, int], dict[str, float]] = {}
    with META_FILE.open("r", newline="", encoding="utf-8-sig") as handle:
        for row in csv.DictReader(handle):
            if row.get("dataset") != "e10gb1":
                continue
            name = row.get("density_name_for_p8_p10", "")
            if name not in {
                "raw_csplit_q070_rmsenv_adaptive",
                "raw_csplit_q070_standardize_rmsenv_adaptive",
            }:
                continue
            try:
                idx = int(float(row.get("raw_efun_index") or row.get("density_index") or "nan"))
            except Exception:
                continue
            out[(name, idx)] = {
                "timescale_sec": safe_float(row.get("timescale_sec_preferred") or row.get("timescale_sec")),
                "frequency_hz": safe_float(row.get("frequency_hz_preferred") or row.get("frequency_hz")),
            }
    return out


def load_top5_rows(meta: dict[tuple[str, int], dict[str, float]]) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    with LONG_FILE.open("r", newline="", encoding="utf-8-sig") as handle:
        for row in csv.DictReader(handle):
            try:
                rank = int(float(row["rank_in_source_csv"]))
                peak = float(row["peak_abs_corr"])
                idx = int(float(row["density_index"]))
            except Exception:
                continue
            if rank > 5 or not math.isfinite(peak):
                continue
            condition = row["condition"]
            md = meta.get((density_name(condition), idx), {})
            rows.append(
                {
                    "condition": condition,
                    "pipeline": row["pipeline"],
                    "feature_family": row["feature_family"],
                    "source_file": row["source_file"],
                    "rank": rank,
                    "component_index": idx,
                    "peak_abs_corr": peak,
                    "timescale_sec": md.get("timescale_sec", math.nan),
                    "frequency_hz": md.get("frequency_hz", math.nan),
                }
            )
    return rows


def aggregate(rows: list[dict[str, object]]) -> list[dict[str, object]]:
    source_counts: dict[tuple[str, str, str], set[str]] = defaultdict(set)
    grouped: dict[tuple[str, str, str, int], dict[str, object]] = defaultdict(
        lambda: {
            "values": [],
            "ranks": [],
            "source_files": set(),
            "timescale_sec": math.nan,
            "frequency_hz": math.nan,
        }
    )
    for row in rows:
        ctx = (
            str(row["condition"]),
            str(row["pipeline"]),
            str(row["feature_family"]),
        )
        source_counts[ctx].add(str(row["source_file"]))
        key = (*ctx, int(row["component_index"]))
        item = grouped[key]
        item["values"].append(float(row["peak_abs_corr"]))  # type: ignore[index, union-attr]
        item["ranks"].append(float(row["rank"]))  # type: ignore[index, union-attr]
        item["source_files"].add(str(row["source_file"]))  # type: ignore[index, union-attr]
        item["timescale_sec"] = float(row["timescale_sec"])
        item["frequency_hz"] = float(row["frequency_hz"])

    summary: list[dict[str, object]] = []
    for key, item in grouped.items():
        condition, pipeline, family, idx = key
        values = np.asarray(item["values"], dtype=float)
        ranks = np.asarray(item["ranks"], dtype=float)
        n_possible = max(1, len(source_counts[(condition, pipeline, family)]))
        source_files = item["source_files"]
        summary.append(
            {
                "condition": condition,
                "pipeline": pipeline,
                "feature_family": family,
                "component_index": idx,
                "top5_occurrence_count": int(values.size),
                "source_file_count": len(source_files),  # type: ignore[arg-type]
                "source_file_fraction": len(source_files) / n_possible,  # type: ignore[arg-type]
                "median_peak_abs_corr": float(np.median(values)),
                "max_peak_abs_corr": float(np.max(values)),
                "mean_rank": float(np.mean(ranks)),
                "timescale_sec": item["timescale_sec"],
                "frequency_hz": item["frequency_hz"],
            }
        )
    summary.sort(
        key=lambda row: (
            str(row["pipeline"]),
            str(row["feature_family"]),
            str(row["condition"]),
            -int(row["top5_occurrence_count"]),
            -float(row["max_peak_abs_corr"]),
        )
    )
    return summary


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields: list[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def selected_components(
    summary: list[dict[str, object]], pipeline: str, family: str, condition: str, mode: str
) -> list[dict[str, object]]:
    rows = [
        row
        for row in summary
        if row["pipeline"] == pipeline
        and row["feature_family"] == family
        and row["condition"] == condition
    ]
    if mode == "count":
        rows.sort(
            key=lambda row: (
                -int(row["top5_occurrence_count"]),
                -float(row["max_peak_abs_corr"]),
                int(row["component_index"]),
            )
        )
    else:
        rows.sort(
            key=lambda row: (
                -float(row["max_peak_abs_corr"]),
                -int(row["top5_occurrence_count"]),
                int(row["component_index"]),
            )
        )
    return rows[:5]


def plot_identity(summary: list[dict[str, object]]) -> Path:
    panel_order = [("P8", "efun"), ("P8", "deconv_efun"), ("P10", "efun"), ("P10", "deconv_efun")]
    conditions = ["nonstandard", "standardized"]
    colors = {"nonstandard": "#1f77b4", "standardized": "#d62728"}
    fig, axes = plt.subplots(len(panel_order), 2, figsize=(13, 13), sharex=False)
    for i, (pipeline, family) in enumerate(panel_order):
        max_count = 1
        picked = {}
        for condition in conditions:
            picked[condition] = selected_components(summary, pipeline, family, condition, "count")
            if picked[condition]:
                max_count = max(max_count, max(int(row["top5_occurrence_count"]) for row in picked[condition]))
        for j, condition in enumerate(conditions):
            ax = axes[i, j]
            rows = picked[condition]
            y = np.arange(len(rows))
            counts = [int(row["top5_occurrence_count"]) for row in rows]
            ax.barh(y, counts, color=colors[condition], alpha=0.75)
            ax.set_yticks(y)
            ax.set_yticklabels([f"idx {row['component_index']}" for row in rows])
            ax.invert_yaxis()
            ax.set_xlim(0, max_count * 1.42)
            ax.grid(axis="x", alpha=0.25)
            if i == 0:
                ax.set_title(condition)
            if j == 0:
                ax.set_ylabel(f"{pipeline} {family}")
            ax.set_xlabel("occurrences in top5 rows")
            for yy, row in zip(y, rows):
                text = (
                    f"med={float(row['median_peak_abs_corr']):.3f}, "
                    f"max={float(row['max_peak_abs_corr']):.3f}, "
                    f"{tau_label(float(row['timescale_sec']))}"
                )
                ax.text(int(row["top5_occurrence_count"]) + max_count * 0.025, yy, text, va="center", fontsize=8)
    fig.suptitle("E10gb1 raw csplit top5 component identity comparison")
    fig.tight_layout()
    out = FIGURE_DIR / "raw_csplit_top5_component_identity_comparison.png"
    fig.savefig(out, dpi=180)
    plt.close(fig)
    return out


def plot_strength(summary: list[dict[str, object]]) -> Path:
    panel_order = [("P8", "efun"), ("P8", "deconv_efun"), ("P10", "efun"), ("P10", "deconv_efun")]
    conditions = ["nonstandard", "standardized"]
    colors = {"nonstandard": "#1f77b4", "standardized": "#d62728"}
    fig, axes = plt.subplots(len(panel_order), 2, figsize=(13, 13), sharex=True)
    for i, (pipeline, family) in enumerate(panel_order):
        for j, condition in enumerate(conditions):
            ax = axes[i, j]
            rows = selected_components(summary, pipeline, family, condition, "strength")
            y = np.arange(len(rows))
            xs = [float(row["max_peak_abs_corr"]) for row in rows]
            sizes = [35 + 12 * math.sqrt(int(row["top5_occurrence_count"])) for row in rows]
            ax.hlines(y, 0, xs, color=colors[condition], alpha=0.35)
            ax.scatter(xs, y, s=sizes, color=colors[condition], alpha=0.85)
            ax.set_yticks(y)
            ax.set_yticklabels(
                [f"idx {row['component_index']}\n{tau_label(float(row['timescale_sec']))}" for row in rows],
                fontsize=8,
            )
            ax.invert_yaxis()
            ax.set_xlim(0, 0.9)
            ax.grid(axis="x", alpha=0.25)
            if i == 0:
                ax.set_title(condition)
            if j == 0:
                ax.set_ylabel(f"{pipeline} {family}")
            ax.set_xlabel("max xcorr peak among top5 rows")
            for yy, row in zip(y, rows):
                ax.text(
                    float(row["max_peak_abs_corr"]) + 0.015,
                    yy,
                    f"n={row['top5_occurrence_count']}, med={float(row['median_peak_abs_corr']):.3f}",
                    va="center",
                    fontsize=8,
                )
    fig.suptitle("E10gb1 raw csplit top5 component strength comparison")
    fig.tight_layout()
    out = FIGURE_DIR / "raw_csplit_top5_component_strength_comparison.png"
    fig.savefig(out, dpi=180)
    plt.close(fig)
    return out


def main() -> None:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    meta = load_metadata()
    rows = load_top5_rows(meta)
    summary = aggregate(rows)
    csv_path = RESULT_DIR / "raw_csplit_top5_component_comparison.csv"
    write_csv(csv_path, summary)
    print(csv_path)
    print(plot_identity(summary))
    print(plot_strength(summary))


if __name__ == "__main__":
    main()
