% Backward-compatible wrapper for pipeline 8 batch coupling/activation export.
%
% Cross-modal activation maps are now generated by the canonical pipeline 8
% batch runner together with the xcorr stage.

warning(['script_generate_missing_bold_activation_maps is now a compatibility wrapper. ', ...
    'Use script_correlate_bold_efuns_with_densities.m for the canonical ', ...
    'pipeline 8 workflow.']);
run(fullfile(fileparts(mfilename('fullpath')), ...
    'script_correlate_bold_efuns_with_densities.m'));
