% Run the current minimal standardized-csplit SOP prerequisites for new F12 data.
%
% Target datasets:
%   f12m02, f12m03, f12m05
%
% Scope:
%   BLP:  complex_split_projected_vlambda_standardize
%   BOLD: roi_mean only
%
% This script runs MATLAB-side prerequisites only:
%   P5 reduction + adaptive-envelope density
%   P7 roi_mean BOLD postprocessing
%   P9 roi_mean BOLD efun/deconv reduction
%   P8/P10 standardized-csplit xcorr
%
% P5 band-selectivity figures and the final minimal consistency summary are
% generated by the companion PowerShell launcher after this MATLAB batch exits.

this_script_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(this_script_dir);
addpath(genpath(repo_root));

close all force;
set(groot, 'defaultFigureVisible', 'off');

target_dataset_stems = {'f12m02', 'f12m03', 'f12m05'};
cfg_names = {'F12m02', 'F12m03', 'F12m05'};
roi_modes = {'roi_mean'};
if ~exist('run_p5_prereqs', 'var') || isempty(run_p5_prereqs)
    run_p5_prereqs = true;
end

fprintf('New F12 standardized-csplit SOP prerequisites\n');
fprintf('  datasets: %s\n', strjoin(target_dataset_stems, ', '));
fprintf('  BLP root: E:\\DataPons_processed\\derived_autodl_results_standardize\n');
fprintf('  BOLD root: E:\\DataPons_processed\\derived_autodl_results_bold_full_export\n');
fprintf('  BOLD modes: %s\n', strjoin(roi_modes, ', '));
fprintf('  run P5 prerequisites: %d\n', logical(run_p5_prereqs));

%% P5: standardized complex-split reduction and adaptive-envelope density.
if logical(run_p5_prereqs)
    run_reduction = true; %#ok<NASGU>
    run_density = true; %#ok<NASGU>
    run_peak_stats = false; %#ok<NASGU>
    skip_existing_reduction = true; %#ok<NASGU>
    skip_existing_density = true; %#ok<NASGU>
    method_filter = {'svd', 'nmf', 'mds', 'umap'}; %#ok<NASGU>
    component_count_sweep = 3:8; %#ok<NASGU>
    time_component_count_sweep = 3:8; %#ok<NASGU>
    spectrum_component_count_sweep = 3:8; %#ok<NASGU>
    autodl_root_override = 'E:\DataPons_processed\derived_autodl_results_standardize'; %#ok<NASGU>
    allow_summary_only_outputs = false; %#ok<NASGU>

    run(fullfile(repo_root, 'scripts', 'script_run_standardized_csplit_p5_for_p12.m'));
end

%% P7: roi_mean BOLD postprocessing from current best summary-only P4 outputs.
for i_cfg = 1:numel(cfg_names)
    cfg_name = cfg_names{i_cfg}; %#ok<NASGU>
    observable_modes = roi_modes; %#ok<NASGU>
    autodl_roots = {'E:\DataPons_processed\derived_autodl_results_bold_full_export'}; %#ok<NASGU>
    allow_summary_only_outputs = false; %#ok<NASGU>
    residual_forms = {}; %#ok<NASGU>
    run_name_filter = {}; %#ok<NASGU>
    run_name_contains = {}; %#ok<NASGU>
    max_runs = []; %#ok<NASGU>
    force_recompute = false; %#ok<NASGU>
    make_main_plot = true; %#ok<NASGU>
    compute_deconv = true; %#ok<NASGU>
    make_deconv_plot = true; %#ok<NASGU>
    make_timescale_plot = true; %#ok<NASGU>
    make_intrinsic_activation_maps = false; %#ok<NASGU>
    make_intrinsic_roi_summary = true; %#ok<NASGU>
    close_figures_after_each_run = true; %#ok<NASGU>
    continue_on_error = true; %#ok<NASGU>

    fprintf('\n[P7 roi_mean] %s\n', cfg_name);
    run(fullfile(repo_root, 'scripts', 'script_run_one_cfg_bold_reskoopnet_postprocessing.m'));
end

%% P9: BOLD efun/deconv reduction for roi_mean, only k05-k08 for current P10.
for i_cfg = 1:numel(cfg_names)
    cfg_name = cfg_names{i_cfg}; %#ok<NASGU>
    observable_modes = roi_modes; %#ok<NASGU>
    current_best_p7_only = true; %#ok<NASGU>
    current_p7_autodl_roots = {'E:\DataPons_processed\derived_autodl_results_bold_full_export'}; %#ok<NASGU>
    current_p7_allow_summary_only_outputs = false; %#ok<NASGU>
    residual_forms = {}; %#ok<NASGU>
    run_name_filter = {}; %#ok<NASGU>
    run_name_contains = {}; %#ok<NASGU>
    max_runs = []; %#ok<NASGU>
    feature_names = {'efun_real', 'deconv_real'}; %#ok<NASGU>
    method_filter = {'svd', 'nmf', 'mds', 'umap'}; %#ok<NASGU>
    component_count_sweep = 5:8; %#ok<NASGU>
    time_component_count_sweep = 5:8; %#ok<NASGU>
    spectrum_component_count_sweep = 5:8; %#ok<NASGU>
    make_summary_plot = false; %#ok<NASGU>
    force_recompute = false; %#ok<NASGU>
    continue_on_error = true; %#ok<NASGU>

    fprintf('\n[P9 roi_mean] %s\n', cfg_name);
    run(fullfile(repo_root, 'scripts', 'script_run_one_cfg_bold_eigenfunction_reduction.m'));
end

%% P8/P10: standardized csplit density coupling, roi_mean only.
main_observable_modes = roi_modes; %#ok<NASGU>
main_feature_names = {'efun_real', 'deconv_real'}; %#ok<NASGU>
main_method_tags = {'svd_k05', 'svd_k06', 'svd_k07', 'svd_k08', ...
    'nmf_k05', 'nmf_k06', 'nmf_k07', 'nmf_k08', ...
    'mds_k05', 'mds_k06', 'mds_k07', 'mds_k08', ...
    'umap_k05', 'umap_k06', 'umap_k07', 'umap_k08'}; %#ok<NASGU>
current_best_roots = {'E:\DataPons_processed\derived_autodl_results_bold_full_export'}; %#ok<NASGU>
residual_forms = {}; %#ok<NASGU>
run_name_filter = {}; %#ok<NASGU>
run_name_contains = {}; %#ok<NASGU>
max_runs = []; %#ok<NASGU>

fprintf('\n[P8 roi_mean standardized csplit]\n');
run(fullfile(repo_root, 'scripts', 'script_run_standardized_csplit_p8_for_p12.m'));

fprintf('\n[P10 roi_mean standardized csplit]\n');
run(fullfile(repo_root, 'scripts', 'script_run_standardized_csplit_p10_for_p12.m'));

fprintf('\nFinished new F12 standardized-csplit SOP prerequisites.\n');
